### PR TITLE
Improvements for Vue and TypeScript

### PR DESCRIPTION
**Pull request by blakewatson**
I added a highlighting for Vue components and for TypeScript types, interfaces, etc.

Screen Shot 2021-04-19 at 12 14 39 PM

Screen Shot 2021-04-19 at 12 17 31 PM

### CODE REVIEW

**Comment by blakewatson** [comment]
I just realized I forgot to update Retro and Shadow, so if these changes seem okay to you I’ll update the other themes.

**Comment by joytrekker** [comment]
Looks good. However before you do any more I'm wondering about the green color in the Vue components. I was thinking it might be nice to make html stand out more when mixed with other languages.

I did a test changing html tags to green. I'm not sold on it though. The original blue/green just looks nicer to me. What do you think? Would it be more helpful to change html tags to something else or keep them the same?

Something like this for php
Screenshot from 2021-04-19 12-02-22
and vue
Screenshot from 2021-04-19 12-15-29

**Comment by blakewatson** [comment]
@joytrekker I agree that the blue tags with green attributes looks nicer. Or maybe I’m just used to it. 😄 That said, I do like having a separate color for `<PascalCaseTags />` because it helps differentiate Vue components from regular tags (assuming you’re using Pascal case). For example in this screenshot, it’s easy to tell which tags are the homemade components versus regular tags and framework tags.

Previously it was a dark green but looks like that color isn’t part of the scheme any more. Playing around with it, I kind of like the pinkish color for those. The light blue I used in my previous screenshot doesn’t contrast as well from regular tags as the pink. What do you think?

Screen Shot 2021-04-19 at 9 26 49 PM

**Comment by joytrekker** [comment]
So after messing around with different colors for far too long your last suggestion looks like the best option to me. The pink Vue components look good and I like keeping html as it is. Regarding the dark green that was removed. I took it out because it was only used in that one scope. I need to take out bright blue as well. Although it seems like I may end up needing to keep one or the other. 

If you don't mind could you edit retro/shadow with the changes? Also all strings should be yellow in the Vue components.

I have a few fixes todo for CSS as well and then I'll push a new update to the marketplace.

**Comment by blakewatson** [comment]
@joytrekker Sounds good. Will do!

Regarding strings in Vue, the attributes in my screenshot that _aren't_ yellow are not actually strings, they're embedded JS code.

**Comment by blakewatson** [comment]
@joytrekker ok I just made those updates across all three themes.

**Pull request merged**
